### PR TITLE
add ts type declarations

### LINKED ISSUE #38: FR: Add typescript typings support
I would like to use this lib in an Angular project and it would be great if I could take advantage of the typings. Thanks.

### PR DESCRIPTION
**Pull request by 5alidz**
should resolve #38

### CODE REVIEW

**Review by bendrucker — COMMENTED** [review]
Thanks! Caught a few issues here with the help of tests. Take a peek and let me know if you spot anything else. Otherwise will release this later in the week.

**Review by 5alidz — COMMENTED** [review]
Looking good, now in the case of using company branded cards, the current way:
```js
const types = [ require('creditcards-types/types/mada') ]
  .concat(require('creditcards-types'))
```
I don't think this will map well the current type:
```ts
withTypes(data: Partial<CardType>[])
```
so type declarations also required in `creditcards-types` Im going to work on that as well

**Comment by bendrucker** [comment]
Anything need to happen here now that https://github.com/bendrucker/creditcards-types/pull/66 is merged? Or is this ready?

**Comment by 5alidz** [comment]
I just copy pasted the same `CardType` for both packages, Just to be cleaner :)

**Pull request merged**
