### PR TITLE
- Reformat js to be more friendly with the ASP.NET minifier

### PR DESCRIPTION
**Pull request by yanigisawa**

### CODE REVIEW

**Comment by bendrucker** [comment]
Sorry, not changing around code to better suit minifiers, especially if they're not super popular

**Comment by bendrucker** [comment]
I'm cleaning up the export syntax in general a bit, hopefully that helps

**Comment by yanigisawa** [comment]
Very well. I was just trying to help since I wasn't the [only one experiencing this issue.](https://github.com/bendrucker/angular-credit-cards/issues/66)

**Comment by bendrucker** [comment]
I'm generally not willing to hack code around like this because I can't make any guarantees about future compatibility. Since I'm not willing to drop in the ASP.NET minifier into the test suite I'm not willing to make changes to support it.

**Comment by bendrucker** [comment]
I'd actually rather you fork if you can't find a build tool/minifier that's capable of handling this. I'd prefer you have a stable and guaranteed hack versus one I might accidentally overwrite a month from now in a patch release and break your app.

**Pull request closed without merging**
